# Números amistosos

## Consigna

Definiendo D(n) como la suma de todos los divisores de n menores a n. Si D(a)=b y D(b)=a, siendo a!=b, entonces podemos decir que a y b son números amigables.

Por ejemplo, los divisores de 220 son: 1, 2, 4, 5, 10, 11, 20, 22, 44, 55 y 110. D(220)=284 y D(284)=220, por lo tanto 220 y 284 son amistosos.

Calcular la sum de todos los números amistosos menores a 10000

## Resolución 

Primero debemos definir una función para calcular D(n).

In [2]:
def divisors_sum(n):
    ## Inicializo las variables
    piv = 1
    sum = 0
    while piv < n:
        if (n%piv)==0:  
            ## piv es divisor de n
            sum += piv
        piv += 1
    
    return sum

Vamos a probar la función

In [4]:
print(220,divisors_sum(220))
print(284,divisors_sum(284))

220 284
284 220


Ahora vamos a hacer un ciclo para recorrer todos los números, calcular su D(n) y verificar son amistosos. 
Dado que cuando calculemos D(220) vamos a definir 220 y 284 como amistosos, vamos a controlar que al pasar por 284, no volvamos a calcular D(284).

In [7]:
amistosos = list() ## Acá guardo los amistosos
N = 10000
suma=0
for i in range(N):
    if i not in amistosos:
        a = divisors_sum(i)
        b = divisors_sum(a)

        if i==b and a!=b:
            amistosos.append(a)
            amistosos.append(b)
            suma+=a+b


In [6]:
amistosos

[284, 220, 1210, 1184, 2924, 2620, 5564, 5020, 6368, 6232]

In [8]:
suma

31626